### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by bert2002** [sabas1080/LibraryEPD#1]
Hi,
I am currently trying to get the display working with a ESP8266 and I wanted to try the example that you provide. Unfortunately the display keeps "white". Compiling is working without any problem.

Does the pin assignment needs to be the same as written in http://www.waveshare.com/wiki/4.3inch_e-Paper#For_Arduino ?

Thanks

bert

**Comment by sabas1080** [comment]
Hi

I have an instructable of this 

http://www.instructables.com/id/E-paper-Display-With-ArduinoESP8266/

 I hope I can help

Cheers

**Comment by bert2002** [comment]
Hi,
found my problem. I used D0 and D1 instead of RX and TX. 

Thanks :)
